### ISSUE TITLE
No indication of existing user when authenticating with Facebook

### ISSUE THREAD

**Issue by mdhornet90** [auth0/Lock-Facebook.iOS#12]
As part of my app's sign up flow, I call [lock identityProviderAuthenticator authenticateWithConnectionName:@"facebook"...]]. This doesn't appear to distinguish between new and existing users, unlike the email/password sign up flow. Are there any strategies for recognizing existing users authenticated through social?

**Comment by hzalaz** [comment]
@mdhornet90 the Auth0 API treats a social signup the same as a regular social login. You could add some logic for the user first's login with a social connection using [Rules](https://auth0.com/docs/rules). Basically will be checking `context` for the connection used to login and the login count. (For more info look [here](https://auth0.com/docs/rules/context))

**Comment by mdhornet90** [comment]
That looks like it'll do the trick. Thanks very much!
